### ISSUE TITLE
Build on Yosemite 10.10 failed.

### ISSUE THREAD

**Issue by supergis** [Ultimaker/cura-build#8]
I compile on Yosemite10.10(Darwin Kernel Version 14.4.0), but got error as:
```
/Users/xxx/devbox/cura-build/build/CuraEngine-prefix/src/CuraEngine/src/utils/polygon.h:37:1: note: 
      did you mean struct here?
class PartsView;
^~~~~
struct
In file included from /Users/xxx/devbox/cura-build/build/CuraEngine-prefix/src/CuraEngine/src/bridge.cpp:4:
In file included from /Users/xxx/devbox/cura-build/build/CuraEngine-prefix/src/CuraEngine/src/sliceDataStorage.h:8:
In file included from /Users/xxx/devbox/cura-build/build/CuraEngine-prefix/src/CuraEngine/src/gcodePlanner.h:10:
/Users/xxx/devbox/cura-build/build/CuraEngine-prefix/src/CuraEngine/src/wallOverlap.h:9:10: fatal error: 
      'hash_fun.h' file not found
#include <hash_fun.h> // hash function object
         ^
1 warning and 1 error generated.
make[5]: *** [CMakeFiles/CuraEngine.dir/src/bridge.cpp.o] Error 1
make[4]: *** [CMakeFiles/CuraEngine.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [CuraEngine-prefix/src/CuraEngine-stamp/CuraEngine-build] Error 2
make[1]: *** [CMakeFiles/CuraEngine.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by mikenew12** [comment]
Same issue here on OS X  10.10.5.

**Comment by awhiemstra** [comment]
Looks like a build issue with master on OSX. Since I have only been building 15.06 on OSX this has not shown up yet. I will look into it.

**Comment by mikenew12** [comment]
@awhiemstra I actually just tried building the 15.06 branch and still get the same error :/

**Comment by awhiemstra** [comment]
That's pretty amazing considering that file does not even exist in 15.06. :) I have just pushed a fix to master that should resolve the build issue.

**Comment by mikenew12** [comment]
Sorry, I must have forgotten to run CMake after switching branches or something. Really appreciate the fix though. It builds perfectly now.
