### ISSUE TITLE
Fails to build in ubuntu 16.04: siplib.c:20:20: fatal error: Python.h: No such file or directory

### ISSUE THREAD

**Issue by elopio** [Ultimaker/cura-build#59]
I'm following the steps in: https://github.com/Ultimaker/cura-build#ubuntulinux
During make I'm getting:
[  4%] Performing build step for 'Sip'
siplib.c:20:20: fatal error: Python.h: No such file or directory
compilation terminated.
Makefile:29: recipe for target 'siplib.o' failed

My steps to reproduce:
$ sudo apt-get install python3 python3-dev python3-pyqt5 python3-pyqt5.qtopengl python3-pyqt5.qtquick python3-pyqt5.qtsvg python3-numpy python3-serial python3-opengl qml-module-qtquick2 qml-module-qtquick-window2 qml-module-qtquick-layouts qml-module-qtquick-dialogs qml-module-qtquick-controls
$ git clone git@github.com:Ultimaker/cura-build.git
$ cd cura-build/
$ mkdir build
$ cd build/
$ cmake ..
$ make

Full make output: https://paste.ubuntu.com/16210245/

**Comment by Ghostkeeper** [comment]
I'd expect the `python3-dev` package to install the Python.h file requested by Sip. Looks like it's not properly setting the include directories.

**Comment by CoderSquirrel** [comment]
I'm having the same problem :/

**Comment by ursula1001** [comment]
It has been a year and this junk is not fixed? Time waster.

**Comment by ursula1001** [comment]
This issue is from last year. This junk is still not fixed? Why waste everyone's time?

**Comment by elopio** [comment]
@ursula1001 I'm sure you know that there are better ways to ask for an status update. This space is to help free software communities. You are just being rude and come with no solutions either, please don't do that.

**Comment by Ghostkeeper** [comment]
One thing you could try is to call `cmake-gui` on the source repository in the Sip-prefix folder, and set the link to the Python header files correctly.

**Comment by LipuFei** [comment]
@elopio Could you try using the latest https://github.com/Ultimaker/cura-build-environment see if this is still a problem? I checked the history that that part of the building scripts have been moved to https://github.com/Ultimaker/cura-build-environment, which creates a build environment to build Cura releases. This repository now only contains build scripts to build a Cura release.

**Comment by LipuFei** [comment]
Closing this issue due to inactivity.
